### ISSUE TITLE
Headliner

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#105]
New 01_TOOL created: Headliner 
Easy-to-use video podcast generator from audio and video raw files with multiple features.

(Log sáb 26 feb 2022 16:35:01 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Tools/Headliner.md

**Comment by joseluis-martin** [comment]
Reviewed and closed

**Comment by joseluis-martin** [comment]
Reviewed and closed
