### ISSUE TITLE
Classroomscreen

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#113]
New 01_TOOL created: Classroomscreen 
Classroomscreen is an online tool that allows you to display the instructions for lesson and lectures in a clear and visual way

(Log sáb 26 feb 2022 16:35:01 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Tools/Classroomscreen.md

**Comment by joseluis-martin** [comment]
Reviewed and closed
