### ISSUE TITLE
RPG Playground

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#114]
New 01_TOOL created: RPG Playground 
Create your game by dragging and dropping items into your world. It is ideal for hobby games, personal projects, school assignments, etc.

(Log sáb 26 feb 2022 16:35:01 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Tools/RPG_Playground.md

**Comment by joseluis-martin** [comment]
Reviewed and closed
