### ISSUE TITLE
Teachable

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#116]
New 01_TOOL created: Teachable 
Create online courses and coaching services. Transform your experience and know-how into a thriving knowledge business.

(Log sáb 26 feb 2022 16:35:01 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Tools/Teachable.md

**Comment by joseluis-martin** [comment]
Reviewed and closed
