### ISSUE TITLE
TED

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#189]
New 02_RESOURCE created: TED 
TED is a nonprofit devoted to spreading ideas, usually in the form of short, powerful talks (18 minutes or less). TED began in 1984 as a conference where Technology, Entertainment and Design converged, and today covers almost all topics — from science to business to global issues — in more than 100 languages. Meanwhile, independently run TEDx events help share ideas in communities around the world.

(Log mar 01 mar 2022 16:04:23 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Resources/TED.md

**Comment by imyelmo** [comment]
Revised
