### ISSUE TITLE
ActivePresenter

### ISSUE THREAD

**Issue by JaviMaciasG** [e-CLOSE/Toolbox#91]
New 01_TOOL created: ActivePresenter 
Record screen, create demos, tutorials, training videos, and interactive HTML5 elearning contents

(Log sáb 26 feb 2022 16:35:01 UTC)
Details at https://github.com/e-CLOSE/Toolbox/blob/main/Tools/ActivePresenter.md

**Comment by imyelmo** [comment]
Revised
